$kind: http-request
name: Create Task
method: POST
url: '{{base_url}}/tasks'
order: 2000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "title": "New Task",
      "description": "Task description",
      "status_id": 1,
      "dt_delivery_limit": "2026-12-31",
      "coordinators_ids": [1, 2]
    }
